nginx:
  build: ./nginx/
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app
php7:
  build: ./php/
  expose:
    - 9000
  links:
    - mariadb
  volumes_from:
    - app
app:
  image: php:7.0-fpm
  volumes:
    - ./src:/var/www/html
  command: "true"

mariadb:
  image: mymariadb:latest
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: project
    MYSQL_USER: project
    MYSQL_PASSWORD: project

data:
  image: mariadb:latest
  volumes:
    - /var/lib/mysql
  command: "true"